### ISSUE TITLE
Add FilterBank.name attribute in dev branch

### ISSUE THREAD

**Issue by ccahilla** [kevinkuns/pytickle#8]
Makes sense to store the name of the filter bank in the FilterBank class, and is useful to not have to pass the filterbank_name with the FilterBank:
(https://github.com/kevinkuns/qlance/blob/1f413e5568e29445d8ec741045ab321ecc10ba27/qlance/filters.py#L680)

**Comment by kevinkuns** [comment]
`FilterBank` classes now have a `name` attribute. When loading a `SOSFilterBank` from a foton file the `filterbank_name` is stored in `name` by default.
